version: '3'

services:
  load_balancer:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - server1
      - server2
      - server3

  server1:
    image: simple-web-server
    container_name: server1
    environment:
      - SERVER_ID=1
    ports:
      - "5001:5000"

  server2:
    image: simple-web-server
    container_name: server2
    environment:
      - SERVER_ID=2
    ports:
      - "5002:5000"

  server3:
    image: simple-web-server
    container_name: server3
    environment:
      - SERVER_ID=3
    ports:
      - "5003:5000"
